### ISSUE TITLE
add more transparent integration

### ISSUE THREAD

**Issue by sellout** [t4ccer/agenix.el#1]
You can have find-file, etc. auto-en/decrypt *.age files, similar to how EasyPG (built into Emacs) does with *.gpg files. `epa-file-enable` or `auto-encryption-mode` are probably good places to start looking.

----
This is something I’m likely to take on myself.

**Comment by t4ccer** [comment]
That sounds useful, I'm out of bandwidth for at least a month unfortunately, but if you'd like to take this feel free!

**Comment by t4ccer** [comment]
I've tried out `auto-encryption-mode` and it's very convenient. That's definitely something that I'd love to see `agenix.el` support
